# Generated by Django 4.2.24 on 2025-09-10 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=400, null=True)),
                ('password1', models.CharField(blank=True, max_length=400, null=True)),
                ('password2', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_image', models.ImageField(default='defult_profile_imagepy/defult_profile.png', upload_to='profile')),
                ('is_saller', models.BooleanField(max_length=50, null=True)),
                ('welcome_notification', models.CharField(max_length=50, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='upload_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video', models.FileField(blank=True, null=True, upload_to='blog content')),
                ('uploder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploder_name', to='Models.profile_model')),
            ],
        ),
        migrations.CreateModel(
            name='upload_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default=True, upload_to='product_image')),
                ('product_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('ammount', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saller', to='Models.profile_model')),
            ],
        ),
        migrations.CreateModel(
            name='send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('seen', models.BooleanField(max_length=100, null=True)),
                ('recever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recever', to='Models.profile_model')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Models.profile_model')),
            ],
        ),
        migrations.CreateModel(
            name='kuriar_dalevery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('customars_phone', models.CharField(blank=True, max_length=400, null=True)),
                ('kuriar_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('kuriar_product_image', models.ImageField(upload_to='kuriar_order_image')),
                ('customars_name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customars_name2', to='Models.profile_model')),
            ],
        ),
        migrations.CreateModel(
            name='home_dalevery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('customars_address', models.CharField(blank=True, max_length=400, null=True)),
                ('customars_phone', models.CharField(blank=True, max_length=400, null=True)),
                ('home_product_image', models.ImageField(upload_to='home_order_image')),
                ('customars_name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customars_name1', to='Models.profile_model')),
            ],
        ),
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_image', models.FileField(blank=True, null=True, upload_to='blog content')),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloger', to='Models.profile_model')),
            ],
        ),
    ]
