# Generated by Django 4.2.24 on 2025-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='profile_image',
            field=models.ImageField(default='defult_profile_image/defult_profile.png', upload_to='profile'),
        ),
    ]
